export const key33: TKeyboardDefinition = {
  id: 'key33',
  name: '33',
  keys: [
    { code: 'KeyQ', x: 0, y: 0 },
    { code: 'KeyW', x: 1, y: 0 },
    { code: 'KeyE', x: 2, y: 0 },
    { code: 'KeyR', x: 3, y: 0 },
    { code: 'KeyT', x: 4, y: 0 },
    { code: 'KeyY', x: 5, y: 0 },
    { code: 'KeyU', x: 6, y: 0 },
    { code: 'KeyI', x: 7, y: 0 },
    { code: 'KeyO', x: 8, y: 0 },
    { code: 'KeyP', x: 9, y: 0 },
    { code: 'BracketLeft', x: 10, y: 0 },
    { code: 'BracketRight', x: 11, y: 0 },
    { code: 'KeyA', x: 0.25, y: 1 },
    { code: 'KeyS', x: 1.25, y: 1 },
    { code: 'KeyD', x: 2.25, y: 1 },
    { code: 'KeyF', x: 3.25, y: 1 },
    { code: 'KeyG', x: 4.25, y: 1 },
    { code: 'KeyH', x: 5.25, y: 1 },
    { code: 'KeyJ', x: 6.25, y: 1 },
    { code: 'KeyK', x: 7.25, y: 1 },
    { code: 'KeyL', x: 8.25, y: 1 },
    { code: 'Semicolon', x: 9.25, y: 1 },
    { code: 'Quote', x: 10.25, y: 1 },
    { code: 'KeyZ', x: 0.75, y: 2 },
    { code: 'KeyX', x: 1.75, y: 2 },
    { code: 'KeyC', x: 2.75, y: 2 },
    { code: 'KeyV', x: 3.75, y: 2 },
    { code: 'KeyB', x: 4.75, y: 2 },
    { code: 'KeyN', x: 5.75, y: 2 },
    { code: 'KeyM', x: 6.75, y: 2 },
    { code: 'Comma', x: 7.75, y: 2 },
    { code: 'Period', x: 8.75, y: 2 },
    { code: 'Slash', x: 9.75, y: 2 },
  ],
}
