import { isMacOS } from '@/env'

export const key47: TKeyboardDefinition = {
  id: 'key47',
  name: '47',
  keys: [
    {
      code: 'Tab',
      x: 0,
      y: 0,
      w: 1.5,
      label: isMacOS ? 'tab' : 'Tab',
      textAlign: 'left',
    },
    { code: 'KeyQ', x: 1.5, y: 0 },
    { code: 'KeyW', x: 2.5, y: 0 },
    { code: 'KeyE', x: 3.5, y: 0 },
    { code: 'KeyR', x: 4.5, y: 0 },
    { code: 'KeyT', x: 5.5, y: 0 },
    { code: 'KeyY', x: 6.5, y: 0 },
    { code: 'KeyU', x: 7.5, y: 0 },
    { code: 'KeyI', x: 8.5, y: 0 },
    { code: 'KeyO', x: 9.5, y: 0 },
    { code: 'KeyP', x: 10.5, y: 0 },
    { code: 'BracketLeft', x: 11.5, y: 0 },
    { code: 'BracketRight', x: 12.5, y: 0 },
    { code: 'Backslash', x: 13.5, y: 0, w: 1.5 },
    {
      code: 'CapsLock',
      x: 0,
      y: 1,
      w: 1.75,
      label: isMacOS ? 'caps lock' : 'Caps Lock',
      textAlign: 'left',
    },
    { code: 'KeyA', x: 1.75, y: 1 },
    { code: 'KeyS', x: 2.75, y: 1 },
    { code: 'KeyD', x: 3.75, y: 1 },
    { code: 'KeyF', x: 4.75, y: 1 },
    { code: 'KeyG', x: 5.75, y: 1 },
    { code: 'KeyH', x: 6.75, y: 1 },
    { code: 'KeyJ', x: 7.75, y: 1 },
    { code: 'KeyK', x: 8.75, y: 1 },
    { code: 'KeyL', x: 9.75, y: 1 },
    { code: 'Semicolon', x: 10.75, y: 1 },
    { code: 'Quote', x: 11.75, y: 1 },
    {
      code: 'Enter',
      x: 12.75,
      y: 1,
      w: 2.25,
      label: isMacOS ? 'return' : 'Enter',
      textAlign: 'right',
    },
    {
      code: 'ShiftLeft',
      x: 0,
      y: 2,
      w: 2.25,
      label: isMacOS ? 'shift' : 'Shift',
      textAlign: 'left',
    },
    { code: 'KeyZ', x: 2.25, y: 2 },
    { code: 'KeyX', x: 3.25, y: 2 },
    { code: 'KeyC', x: 4.25, y: 2 },
    { code: 'KeyV', x: 5.25, y: 2 },
    { code: 'KeyB', x: 6.25, y: 2 },
    { code: 'KeyN', x: 7.25, y: 2 },
    { code: 'KeyM', x: 8.25, y: 2 },
    { code: 'Comma', x: 9.25, y: 2 },
    { code: 'Period', x: 10.25, y: 2 },
    { code: 'Slash', x: 11.25, y: 2 },
    {
      code: 'ShiftRight',
      x: 12.25,
      y: 2,
      w: 2.75,
      label: isMacOS ? 'shift' : 'Shift',
      textAlign: 'right',
    },
    {
      code: 'ControlLeft',
      x: 0,
      y: 3,
      w: 1.25,
      label: isMacOS ? '⌃' : 'Ctrl',
      textAlign: 'left',
    },
    {
      code: 'MetaLeft',
      x: 1.25,
      y: 3,
      w: 1.25,
      label: isMacOS ? '⌘' : 'Win',
      textAlign: 'left',
    },
    {
      code: 'AltLeft',
      x: 2.5,
      y: 3,
      w: 1.25,
      label: isMacOS ? '⌥' : 'Alt',
      textAlign: 'left',
    },
    { code: 'Space', x: 3.75, y: 3, w: 6.25 },
    {
      code: 'AltRight',
      x: 10,
      y: 3,
      w: 1.25,
      label: isMacOS ? '⌥' : 'Alt',
      textAlign: 'left',
    },
    {
      code: 'MetaRight',
      x: 11.25,
      y: 3,
      w: 1.25,
      label: isMacOS ? '⌘' : 'Win',
      textAlign: 'left',
    },
    {
      code: 'Fn',
      x: 12.5,
      y: 3,
      w: 1.25,
      label: isMacOS ? 'fn' : 'Fn',
      textAlign: 'left',
    },
    {
      code: 'ControlRight',
      x: 13.75,
      y: 3,
      w: 1.25,
      label: isMacOS ? '⌃' : 'Ctrl',
      textAlign: 'left',
    },
  ],
  spaceVariants: {
    space1: [{ code: 'Space', w: 6.25 }],
    space2: [
      { code: 'Space', w: 3 },
      { code: 'SpaceSplit1', w: 3.25 },
    ],
    space3: [
      { code: 'Space', w: 2.25 },
      { code: 'SpaceSplit1', w: 1.25 },
      { code: 'SpaceSplit2', w: 2.75 },
    ],
  },
}
