export const key45: TKeyboardDefinition = {
  id: 'key45',
  name: '45',
  keys: [
    { code: 'Digit1', x: 0, y: 0 },
    { code: 'Digit2', x: 1, y: 0 },
    { code: 'Digit3', x: 2, y: 0 },
    { code: 'Digit4', x: 3, y: 0 },
    { code: 'Digit5', x: 4, y: 0 },
    { code: 'Digit6', x: 5, y: 0 },
    { code: 'Digit7', x: 6, y: 0 },
    { code: 'Digit8', x: 7, y: 0 },
    { code: 'Digit9', x: 8, y: 0 },
    { code: 'Digit0', x: 9, y: 0 },
    { code: 'Minus', x: 10, y: 0 },
    { code: 'Equal', x: 11, y: 0 },
    { code: 'Backslash', x: 12, y: 0, w: 1 },
    { code: 'KeyQ', x: 0.5, y: 1 },
    { code: 'KeyW', x: 1.5, y: 1 },
    { code: 'KeyE', x: 2.5, y: 1 },
    { code: 'KeyR', x: 3.5, y: 1 },
    { code: 'KeyT', x: 4.5, y: 1 },
    { code: 'KeyY', x: 5.5, y: 1 },
    { code: 'KeyU', x: 6.5, y: 1 },
    { code: 'KeyI', x: 7.5, y: 1 },
    { code: 'KeyO', x: 8.5, y: 1 },
    { code: 'KeyP', x: 9.5, y: 1 },
    { code: 'BracketLeft', x: 10.5, y: 1 },
    { code: 'BracketRight', x: 11.5, y: 1 },
    { code: 'KeyA', x: 0.75, y: 2 },
    { code: 'KeyS', x: 1.75, y: 2 },
    { code: 'KeyD', x: 2.75, y: 2 },
    { code: 'KeyF', x: 3.75, y: 2 },
    { code: 'KeyG', x: 4.75, y: 2 },
    { code: 'KeyH', x: 5.75, y: 2 },
    { code: 'KeyJ', x: 6.75, y: 2 },
    { code: 'KeyK', x: 7.75, y: 2 },
    { code: 'KeyL', x: 8.75, y: 2 },
    { code: 'Semicolon', x: 9.75, y: 2 },
    { code: 'Quote', x: 10.75, y: 2 },
    { code: 'KeyZ', x: 1.25, y: 3 },
    { code: 'KeyX', x: 2.25, y: 3 },
    { code: 'KeyC', x: 3.25, y: 3 },
    { code: 'KeyV', x: 4.25, y: 3 },
    { code: 'KeyB', x: 5.25, y: 3 },
    { code: 'KeyN', x: 6.25, y: 3 },
    { code: 'KeyM', x: 7.25, y: 3 },
    { code: 'Comma', x: 8.25, y: 3 },
    { code: 'Period', x: 9.25, y: 3 },
    { code: 'Slash', x: 10.25, y: 3 },
  ],
}
