import { isMacOS } from '@/env'

export const key96a: TKeyboardDefinition = {
  id: 'key96a',
  name: '96a',
  keys: [
    // y=0: Function row
    {
      code: 'Escape',
      x: 0,
      y: 0,
      w: 1,
      label: isMacOS ? 'esc' : 'Esc',
      textAlign: 'left',
    },
    { code: 'F1', x: 1, y: 0, w: 1 },
    { code: 'F2', x: 2, y: 0, w: 1 },
    { code: 'F3', x: 3, y: 0, w: 1 },
    { code: 'F4', x: 4, y: 0, w: 1 },
    { code: 'F5', x: 5, y: 0, w: 1 },
    { code: 'F6', x: 6, y: 0, w: 1 },
    { code: 'F7', x: 7, y: 0, w: 1 },
    { code: 'F8', x: 8, y: 0, w: 1 },
    { code: 'F9', x: 9, y: 0, w: 1 },
    { code: 'F10', x: 10, y: 0, w: 1 },
    { code: 'F11', x: 11, y: 0, w: 1 },
    { code: 'F12', x: 12, y: 0, w: 1 },
    { code: 'Insert', x: 13, y: 0, w: 1 },
    { code: 'Delete', x: 14, y: 0, w: 1 },
    { code: 'Home', x: 15, y: 0 },
    { code: 'End', x: 16, y: 0 },
    { code: 'PageUp', x: 17, y: 0 },
    { code: 'PageDown', x: 18, y: 0 },
    // y=1: Number row (numpad: NumLock / * -)
    { code: 'Backquote', x: 0, y: 1 },
    { code: 'Digit1', x: 1, y: 1 },
    { code: 'Digit2', x: 2, y: 1 },
    { code: 'Digit3', x: 3, y: 1 },
    { code: 'Digit4', x: 4, y: 1 },
    { code: 'Digit5', x: 5, y: 1 },
    { code: 'Digit6', x: 6, y: 1 },
    { code: 'Digit7', x: 7, y: 1 },
    { code: 'Digit8', x: 8, y: 1 },
    { code: 'Digit9', x: 9, y: 1 },
    { code: 'Digit0', x: 10, y: 1 },
    { code: 'Minus', x: 11, y: 1 },
    { code: 'Equal', x: 12, y: 1 },
    {
      code: 'Backspace',
      x: 13,
      y: 1,
      w: 2,
      label: isMacOS ? 'delete' : 'Backspace',
      textAlign: 'right',
    },
    { code: 'NumLock', x: 15, y: 1 },
    { code: 'NumpadDivide', x: 16, y: 1 },
    { code: 'NumpadMultiply', x: 17, y: 1 },
    { code: 'NumpadSubtract', x: 18, y: 1 },
    // y=2: Tab row (numpad: 7 8 9 +)
    {
      code: 'Tab',
      x: 0,
      y: 2,
      w: 1.5,
      label: isMacOS ? 'tab' : 'Tab',
      textAlign: 'left',
    },
    { code: 'KeyQ', x: 1.5, y: 2 },
    { code: 'KeyW', x: 2.5, y: 2 },
    { code: 'KeyE', x: 3.5, y: 2 },
    { code: 'KeyR', x: 4.5, y: 2 },
    { code: 'KeyT', x: 5.5, y: 2 },
    { code: 'KeyY', x: 6.5, y: 2 },
    { code: 'KeyU', x: 7.5, y: 2 },
    { code: 'KeyI', x: 8.5, y: 2 },
    { code: 'KeyO', x: 9.5, y: 2 },
    { code: 'KeyP', x: 10.5, y: 2 },
    { code: 'BracketLeft', x: 11.5, y: 2 },
    { code: 'BracketRight', x: 12.5, y: 2 },
    { code: 'Backslash', x: 13.5, y: 2, w: 1.5 },
    { code: 'Numpad7', x: 15, y: 2 },
    { code: 'Numpad8', x: 16, y: 2 },
    { code: 'Numpad9', x: 17, y: 2 },
    { code: 'NumpadAdd', x: 18, y: 2, w: 1, h: 2 },
    // y=3: Caps row (numpad: 4 5 6)
    {
      code: 'CapsLock',
      x: 0,
      y: 3,
      w: 1.75,
      label: isMacOS ? 'caps lock' : 'Caps Lock',
      textAlign: 'left',
    },
    { code: 'KeyA', x: 1.75, y: 3 },
    { code: 'KeyS', x: 2.75, y: 3 },
    { code: 'KeyD', x: 3.75, y: 3 },
    { code: 'KeyF', x: 4.75, y: 3 },
    { code: 'KeyG', x: 5.75, y: 3 },
    { code: 'KeyH', x: 6.75, y: 3 },
    { code: 'KeyJ', x: 7.75, y: 3 },
    { code: 'KeyK', x: 8.75, y: 3 },
    { code: 'KeyL', x: 9.75, y: 3 },
    { code: 'Semicolon', x: 10.75, y: 3 },
    { code: 'Quote', x: 11.75, y: 3 },
    {
      code: 'Enter',
      x: 12.75,
      y: 3,
      w: 2.25,
      label: isMacOS ? 'return' : 'Enter',
      textAlign: 'right',
    },
    { code: 'Numpad4', x: 15, y: 3 },
    { code: 'Numpad5', x: 16, y: 3 },
    { code: 'Numpad6', x: 17, y: 3 },
    // y=4: Shift row + arrow up (numpad: 1 2 3 Enter)
    {
      code: 'ShiftLeft',
      x: 0,
      y: 4,
      w: 2.25,
      label: isMacOS ? 'shift' : 'Shift',
      textAlign: 'left',
    },
    { code: 'KeyZ', x: 2.25, y: 4 },
    { code: 'KeyX', x: 3.25, y: 4 },
    { code: 'KeyC', x: 4.25, y: 4 },
    { code: 'KeyV', x: 5.25, y: 4 },
    { code: 'KeyB', x: 6.25, y: 4 },
    { code: 'KeyN', x: 7.25, y: 4 },
    { code: 'KeyM', x: 8.25, y: 4 },
    { code: 'Comma', x: 9.25, y: 4 },
    { code: 'Period', x: 10.25, y: 4 },
    { code: 'Slash', x: 11.25, y: 4 },
    {
      code: 'ShiftRight',
      x: 12.25,
      y: 4,
      w: 1.75,
      label: isMacOS ? 'shift' : 'Shift',
      textAlign: 'right',
    },
    { code: 'ArrowUp', x: 14, y: 4 },
    { code: 'Numpad1', x: 15, y: 4 },
    { code: 'Numpad2', x: 16, y: 4 },
    { code: 'Numpad3', x: 17, y: 4 },
    {
      code: 'NumpadEnter',
      x: 18,
      y: 4,
      w: 1,
      h: 2,
      label: isMacOS ? 'return' : 'Enter',
      textAlign: 'center',
    },
    // y=5: Bottom row + arrows (numpad: 0 .)
    {
      code: 'ControlLeft',
      x: 0,
      y: 5,
      w: 1.25,
      label: isMacOS ? '⌃' : 'Ctrl',
      textAlign: 'left',
    },
    {
      code: 'MetaLeft',
      x: 1.25,
      y: 5,
      w: 1.25,
      label: isMacOS ? '⌘' : 'Win',
      textAlign: 'left',
    },
    {
      code: 'AltLeft',
      x: 2.5,
      y: 5,
      w: 1.25,
      label: isMacOS ? '⌥' : 'Alt',
      textAlign: 'left',
    },
    { code: 'Space', x: 3.75, y: 5, w: 6.25 },
    {
      code: 'AltRight',
      x: 10,
      y: 5,
      w: 1.25,
      label: isMacOS ? '⌥' : 'Alt',
      textAlign: 'left',
    },
    {
      code: 'Fn',
      x: 11.25,
      y: 5,
      w: 1.25,
      label: isMacOS ? 'fn' : 'Fn',
      textAlign: 'left',
    },
    { code: 'ArrowLeft', x: 13, y: 5 },
    { code: 'ArrowDown', x: 14, y: 5 },
    { code: 'ArrowRight', x: 15, y: 5 },
    { code: 'Numpad0', x: 16, y: 5, w: 1 },
    { code: 'NumpadDecimal', x: 17, y: 5 },
  ],
  spaceVariants: {
    space1: [{ code: 'Space', w: 6.25 }],
    space2: [
      { code: 'Space', w: 3 },
      { code: 'SpaceSplit1', w: 3.25 },
    ],
    space3: [
      { code: 'Space', w: 2.25 },
      { code: 'SpaceSplit1', w: 1.25 },
      { code: 'SpaceSplit2', w: 2.75 },
    ],
  },
}
